### ISSUE TITLE
Not compatible with `set autochdir`

### ISSUE THREAD

**Issue by rafaeln** [tpope/vim-flagship#10]
By the way, thanks for the great and minimalist plugin. I'm a fan. Now, to the issue:

Using the following `.vimrc`

``` vimscript
filetype plugin on
runtime bundle/vim-pathogen/autoload/pathogen.vim
let g:pathogen_disabled = []
let g:pathogen_disabled = split(system('ls ~/.vim/bundle/'))
call remove(g:pathogen_disabled, index(g:pathogen_disabled, 'vim-flagship'))
execute pathogen#infect()
set laststatus=2
set showtabline=2
set guioptions-=e
set autochdir
```

and opening vim as `vim --servername s`, 
then doing the following on another terminal

``` bash
mkdir dir1 dir2
touch dir1/file1 dir2/file2
vim --servername s --remote-tab dir1/file1 dir2/file2
```

Whichever tab I switch to, tabline will be repeating that tab's directory for every tab:

![screenshot from 2015-09-23 10 57 34](https://cloud.githubusercontent.com/assets/2940362/10046941/fd0c02a6-61e1-11e5-8238-734387f8670e.png)

![screenshot from 2015-09-23 10 57 48](https://cloud.githubusercontent.com/assets/2940362/10046934/f7684e68-61e1-11e5-9adf-141ab9da5e34.png)

**Comment by tpope** [comment]
`autochdir` changes the _global_ current working directory every time you switch files. So, what flagship is reporting is a correct representation of the state of Vim. If you want to try to add some `'autochdir'` contingent special casing, be my guest.

**Comment by tpope** [comment]
Not that it helps you right now but I have a not yet released companion plugin that helps you set a per project cwd automatically, without requiring the sledgehammer that is autochdir.

**Comment by rafaeln** [comment]
I see. I was under the uneducated impression that `&autochdir` was
equivalent to

```vim
augroup vimrc
  autocmd!
  autocmd BufEnter * execute expand('%') == "" ? "" : "lcd %:p:h"
augroup END
```

But there's still something I'm not getting: if I substitute `set
autochdir` in the minimal `.vimrc` for the `augroup` given above, I still
get problems:

`vim --servername vim`

tabline: vim *1 ~*

`vim --servername vim --remote-tab dir1/file1

tabline: vim *1 ~*

`vim --servername vim --remote-tab dir2/file2`

tabline: vim 1 ~ *2 dir2*

`vim --servername vim --remote-tab dir3/file3`

tabline: vim 1 ~ 2 ~ *3 dir3*

`gT`

tabline: vim 1 ~ *2 dir2* 3 dir3

`gT`

tabline: vim *1 dir1* 2 dir2 3 dir3

**Comment by rafaeln** [comment]
I see. I was under the uneducated impression that `&autochdir` was equivalent to

``` vim
augroup vimrc
  autocmd!
  autocmd BufEnter * execute expand('%') == "" ? "" : "lcd %:p:h"
augroup END
```

If I remove `set autochdir` from the minimal `.vimrc` I gave previously and add the `augroup` given above, I still get problems, though:

`vim --servername vim`

_tabline:_ vim **1 ~**

`vim --servername vim --remote-tab dir1/file1`

_tabline:_ vim **1 ~**

`vim --servername vim --remote-tab dir2/file2`

_tabline:_ vim 1 ~ **2 dir2**

`vim --servername vim --remote-tab dir3/file3`

_tabline:_ vim 1 ~ 2 ~ **3 dir3**

`gT`

_tabline:_ vim 1 ~ **2 dir2** 3 dir3

`gT`

_tabline:_ vim **1 dir1** 2 dir2 3 dir3

**Comment by tpope** [comment]
No it's not, it uses `cd` not `lcd`. Also, from the help:

```
This option is provided for backward compatibility with the Vim
released with Sun ONE Studio 4 Enterprise Edition.
Note: When this option is on some plugins may not work.
```

It's legacy garbage, use it at your own risk.

**Comment by rafaeln** [comment]
I see. So, what settings do you recommend for best compatibility with _vim-flagship_?
