### ISSUE TITLE
Disable fugitive statusline display

### ISSUE THREAD

**Issue by whiteinge** [tpope/vim-flagship#11]
Flagship automatically adds the Fugitive `[Git(master)]` information to the statusline (stock Vim statusline; no customizations). Skimming the code I don't see that this behavior is configurable in either plugin.

Can the Fugitive statusline be disabled?

**Comment by tpope** [comment]
There is an undocumented `g:flagship_skip` option which can be set to a regexp matching any flags you want to opt out of.

```
let g:flagship_skip = 'fugitive#statusline\|FugitiveStatusline'
```

**Comment by whiteinge** [comment]
Sure enough. I missed it. Works like a charm. Thank you!

**Comment by urbainvaes** [comment]
Does this still work? The fix didn't work for me... Also, would it be possible to set the highlight group of the default elements to `Statusline`?

**Comment by tpope** [comment]
The function recently got renamed to `FugitiveStatusline`.

I don't understand your second question, isn't the statusline always `Statusline`? You should be able to embed any `%#HLname#` specifiers you want.

**Comment by urbainvaes** [comment]
I was referring to the fact that, without any configuration, the
fugitive flag in flagship's default statusline,

    %{flagship#in(winnr()==1?1:-1)}%<%{flagship#filename()} %{flagship#surround(flagship#filetype())}%w%m%r%##%{flagship#call('FugitiveStatusline')}%*%= %-14.(%l,%c%V%) %P%{flagship#in(0)}

stands out, and I was wondering whether this was desirable -- is there a reason
for the presence of '%##' before %{flagship#call('FugitiveStatusline')}?

**Comment by tpope** [comment]
That shouldn't be there. What does `:echo hlexists('')` return for you?

**Comment by urbainvaes** [comment]
It returns 1. But in fact I realize that, without vim-gitgutter, the
command returns 1 and the fugitive flag is highlighted as expected, so
the bug might be in gitgutter?

Anyway, thank you very much for your help.

**Comment by tpope** [comment]
Freaking weird, why does Vim think an empty string highlight group exists? Easy enough to work around.

No idea why vim-gitgutter would have anything to do with this, unless maybe it incidentally removes the `%##` from the statusline.

**Comment by urbainvaes** [comment]
Sorry, I meant to say that, without gitgutter, the command returns 0 (i.e., the flags are highlighted as expected.) 

I have no idea why...

And thanks, the last commit fixes the problem. :)

**Comment by tpope** [comment]
Oh, well at least there's a culprit....
