### ISSUE TITLE
Flag for trailing whitespaces

### ISSUE THREAD

**Issue by urbainvaes** [tpope/vim-flagship#12]
Hello!

First, thank you for this plugin and the others!

I am trying to add a flag to indicate if there is any trailing white-space in the current file. For this, I have added the line 

`autocmd User Flags call Hoist("window", "%{search('\\s\\+$','pn')?'[tw]':''}")` 

to my .vimrc, which works fine apart from the fact that the flag updates at each keystroke, whereas I would prefer it to update only when saving. Is is possible to make it behave this way?

Thank you!

**Comment by tpope** [comment]
If you want to that you'll have to cache the value yourself.

**Comment by urbainvaes** [comment]
Exactly what I was looking for, thanks!
