### ISSUE TITLE
show remote branch status in flagship

### ISSUE THREAD

**Issue by gauteh** [tpope/vim-flagship#15]
this might be of interest: a small statusline indicator to show whether the current branch is uptodate with its remote: https://github.com/gauteh/vim-remote-status

depends on fugitive as well, hopefully this doesn't already exist within fugitive, but I doubt it because of the `remote update`shenanigans (if it doesn't and it would be interesting there, let me know). on the other hand, it would be amazing if `fugitive#ReloadStatus` triggers some event I could hook into since updating the status is a little bit unreliable now.

![remote-status](https://user-images.githubusercontent.com/56827/45596810-3f348280-b9c2-11e8-8420-342694def3c2.png)

**Comment by tpope** [comment]
Fugitive doesn't have anything like this. I think it would be a nice addition, but it needs to be done without spamming `system()` calls, because that can make Vim really sluggish.

As far as the hook you are looking for, I would expect that `BufReadPost index` would be good enough.

**Comment by gauteh** [comment]
Tim Pope writes on September 17, 2018 19:22:
> Fugitive doesn't have anything like this. I think it would be a nice addition, but it needs to be done without spamming `system()` calls, because that can make Vim really sluggish.

Yup, currently it is caching the status and updating on-demand. But I 
can see that it might become sluggish since probably lots of stuff try 
to update on the same kind of events. Not sure how to avoid the 
`merge-base` call though.. seems to be fast enough atm.

> As far as the hook you are looking for, I would expect that `BufReadPost index` would be good enough.
> 

Thanks, good suggestion. BufReadPost index seems to be a good choice.

**Comment by tpope** [comment]
You can't avoid the `merge-base` call but you can avoid calling it over and over again with the same arguments. Otherwise, I'll accept "fast enough" if you test it on a thrashing Windows machine.

I should probably go ahead and clarify that the "run `git remote update` repeatedly" part of things isn't something that I think belongs in Fugitive.

**Comment by gauteh** [comment]
Tim Pope writes on September 21, 2018 17:48:
> You can't avoid the `merge-base` call but you can avoid calling it over and over again with the same arguments. Otherwise, I'll accept "fast enough" if you test it on a thrashing Windows machine.
> 
> I should probably go ahead and clarify that the "run `git remote update` repeatedly" part of things isn't something that I think belongs in Fugitive.

Yeah, I can see that.
