### ISSUE TITLE
How to add white-space as a separator between tab labels?

### ISSUE THREAD

**Issue by Asheq** [tpope/vim-flagship#16]
The tab labels sit directly next to each other, making it sometimes hard to see when one ends and another begins (depending on the content):
![image](https://user-images.githubusercontent.com/4657140/62650378-a1181680-b90b-11e9-8a68-8104deb8d02c.png)

Is there a way to add white-space as a separator between tab labels?
 
As an example, here is my tmux status line:
![image](https://user-images.githubusercontent.com/4657140/62650428-b725d700-b90b-11e9-94f6-350aeabbb538.png)

which uses the following (default) option to add a space as a separator:
```
set-option -g window-status-separator ' '
```

**Comment by tpope** [comment]
This isn't currently supported, but I think `g:tabinfix` would be a pretty natural addition, if you want to try adding it to `flagship#tablabels()`.

**Comment by Asheq** [comment]
Sure, I'll take a look when I get a chance. Thanks for being open to it.

**Comment by Asheq** [comment]
Closing since it is addressed.
