### ISSUE TITLE
Switching current directory to non-home ends up confusing the tab bar

### ISSUE THREAD

**Issue by aripollak** [tpope/vim-flagship#3]
I think I found a bug in the latest addition for #2 - if I open up vim from my home directory and do this:

``` vim
:e .vimrc
:tabnew 
:cd hi
```

Then the tab line looks like this, which seems wrong, since it loses both the filename and the directory of the first tab:

```
  1 ~/hi  2 ~/hi
```

**Comment by tpope** [comment]
`:cd` changes the global directory so it affects the first tab too. You're probably looking for `:lcd`.

**Comment by aripollak** [comment]
Maybe, but isn't the first tab label still incorrect? I would still expect it to say ~/.vimrc, or some shortening thereof.

mmm, shortening.
