### ISSUE TITLE
Recommended options set by default anyway?

### ISSUE THREAD

**Issue by aripollak** [tpope/vim-flagship#4]
The README recommends setting these:

```
    set laststatus=2
    set showtabline=2
    set guioptions-=e
```

However, the plugin ends up setting those by default anyway. Seems those should be kept up to the reader to set?

**Comment by tpope** [comment]
As elaborated on in the docs, if you do zero customization of any related options, it assumed you want the recommended defaults and sets them for you.

**Comment by aripollak** [comment]
Hm, that line in the doc seems worth mentioning in the README.
