### ISSUE TITLE
can't use showtabline=1 ?

### ISSUE THREAD

**Issue by aleprovencio** [tpope/vim-flagship#7]
Hello, vim-flagship auto sets showtabline=2, is there a way i can use showtabline=1 on my vimrc?

**Comment by tpope** [comment]
This behavior is automatically disabled once you define a custom `tabprefix` or `tablabel`. But I guess that's still a bit aggressive, so I'm pushing a change that will respect `showtabline=1` if you explicitly set it in your vimrc.

**Comment by aleprovencio** [comment]
That's awesome, thank you
