### ISSUE TITLE
Flagship modifies existing statusline

### ISSUE THREAD

**Issue by rdlugosz** [tpope/vim-flagship#8]
I have a fairly customized `statusline` (see these lines of [my vimrc](https://github.com/rdlugosz/dotfiles/blob/master/vimrc#L584)) and when I enable the Flagship plugin I see a duplicate section for Fugitive. Based on the mention in the readme that _customizing your status line is exactly the same with and without Flagship_, I did not expect this behavior.

Without Flagship:
<img width="738" alt="screen shot 2015-07-23 at 5 22 18 pm" src="https://cloud.githubusercontent.com/assets/402328/8862568/6b5a8fa6-315f-11e5-81f8-1435a0a72658.png">

**With** Flagship:
<img width="740" alt="screen shot 2015-07-23 at 5 20 30 pm" src="https://cloud.githubusercontent.com/assets/402328/8862557/49acf132-315f-11e5-8341-4714da47d6b4.png">

Thanks!!

**Comment by bohrshaw** [comment]
@rdlugosz `autocmd User Flags set statusline=your_statusline` would do it.

**Comment by tpope** [comment]
I guess the short answer is that text refers to _customization_ and not _extension_. You could use `g:flagship_skip` to achieve the desired effect, but if the underlying problem is you want precise control over the order and position of plugin flags, Flagship probably isn't for you.

I don't see the point of `autocmd User Flags set statusline=your_statusline`; seems the same as uninstalling the plugin entirely.

**Comment by bohrshaw** [comment]
@tpope
I have a highly customized `statusline` and _extension_ of it doesn't work for me. But the Flagship `tabline` is glorious and perfectly fits in my setup.

I see that `flagship#statusline(...)` has some [plumbing codes](https://github.com/tpope/vim-flagship/blob/ed70fc9f070cf0b476ce287b732b523f15ba07cc/autoload/flagship.vim#L421), apart from injecting flags. **If there's a way(a public function) to cleanly do the plumbing in the `statusline`, that would be nice.** The command `let g:flagship_skip = '.'` essentially disables all flags, but that's a post-thought for my need.

**Comment by tpope** [comment]
Oh yeah didn't consider the tabline only use case.

Could we move some of the plumbing into `flagship#in()` such that you'd be reduced to calling of `flagship#in(tabpagenr(), winnr())` or even `flagship#in(-winnr())`? That seems like a good first step.

**Comment by bohrshaw** [comment]
Yes, the first step is to twist the pipe outward. And thanks for considering this use case!
