### ISSUE TITLE
Adding arglist to statusline

### ISSUE THREAD

**Issue by Hotschke** [tpope/vim-flagship#9]
Is it possible to add the arglist to the flagship line?

Something like this (does not work)

``` viml
autocmd User Flags call Hoist("global", ":args")
```

**Comment by tpope** [comment]
There's not a one liner for it but could stitch something together using `argc()` and `argv()`. Try:

``` vim
function ArgString() abort
  return join(map(range(argc()), 'argv(v:val)'), ' ')
endfunction

autocmd User Flags call Hoist("global", "ArgString")
```

**Comment by Hotschke** [comment]
Thank you very much.

However, I am not sure how to incorporate this with the shown filename.

D. Neil has promoted in his screencasts the `arglist`. I like the idea, but I don't feel yet comfortable with a manually managed list which does not survive a restart of vim and I easily forget what I have added. I was hoping when I see the list it would become more handy (e.g. for search&replace, file switching and probably other things).

Anyhow, thanks again.
